frontend:
  image: rselvanathan/unicorn-frontend:${fe_version}
  mem_limit: 100288000
  ports:
    - "80:8080"
  links:
    - backend
  environment:
    BACKEND_HOST: backend
    BACKEND_PORT: 8080

backend:
  image: rselvanathan/unicorn-backend:${be_version} 
  mem_limit: 200288000
  ports:
    - "8888:8080"
  environment:
    spring.data.mongodb.uri: mongodb://54.229.163.232:27017/unicodn

